apiVersion: v1
kind: Service
metadata:
  name: esproxy
  labels:
    app: esproxy
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
      name: http
  selector:
    app: esproxy
